src/Entity/Receta.php
<?php

namespace App\Entity;

use App\Repository\RecetaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RecetaRepository::class)]
class Receta
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $fecha = null;

    #[ORM\Column(length: 255)]
    private ?string $tipo_receta = null;

    #[ORM\ManyToOne(inversedBy: 'recetas')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Usuario $id_usuario = null;

    #[ORM\ManyToMany(targetEntity: Ingrediente::class, inversedBy: 'recetas')]
    private Collection $id_ingrediente;

    #[ORM\OneToMany(mappedBy: 'receta', targetEntity: Foto::class)]
    private Collection $id_foto;

    #[ORM\Column(length: 255)]
    private ?string $nombre = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $descripcion = null;

    public function __construct()
    {
        $this->id_ingrediente = new ArrayCollection();
        $this->id_foto = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFecha(): ?\DateTimeInterface
    {
        return $this->fecha;
    }

    public function setFecha(\DateTimeInterface $fecha): self
    {
        $this->fecha = $fecha;

        return $this;
    }

    public function getTipoReceta(): ?string
    {
        return $this->tipo_receta;
    }

    public function setTipoReceta(string $tipo_receta): self
    {
        $this->tipo_receta = $tipo_receta;

        return $this;
    }

    public function getIdUsuario(): ?Usuario
    {
        return $this->id_usuario;
    }

    public function setIdUsuario(?Usuario $id_usuario): self
    {
        $this->id_usuario = $id_usuario;

        return $this;
    }

    /**
     * @return Collection<int, Ingrediente>
     */
    public function getIdIngrediente(): Collection
    {
        return $this->id_ingrediente;
    }

    public function addIdIngrediente(Ingrediente $idIngrediente): self
    {
        if (!$this->id_ingrediente->contains($idIngrediente)) {
            $this->id_ingrediente->add($idIngrediente);
        }

        return $this;
    }

    public function removeIdIngrediente(Ingrediente $idIngrediente): self
    {
        $this->id_ingrediente->removeElement($idIngrediente);

        return $this;
    }

    /**
     * @return Collection<int, Foto>
     */
    public function getIdFoto(): Collection
    {
        return $this->id_foto;
    }

    public function addIdFoto(Foto $idFoto): self
    {
        if (!$this->id_foto->contains($idFoto)) {
            $this->id_foto->add($idFoto);
            $idFoto->setReceta($this);
        }

        return $this;
    }

    public function removeIdFoto(Foto $idFoto): self
    {
        if ($this->id_foto->removeElement($idFoto)) {
            // set the owning side to null (unless already changed)
            if ($idFoto->getReceta() === $this) {
                $idFoto->setReceta(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->nombre;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(string $descripcion): self
    {
        $this->descripcion = $descripcion;

        return $this;
    }
}

src/Controller/RecetaController.php
<?php

namespace App\Controller;

use App\Entity\Receta;
use App\Form\Receta1Type;
use App\Repository\RecetaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Routing\Annotation\Route;

use App\Entity\Foto;
use App\Repository\FotoRepository;

#[Route('/receta')]
class RecetaController extends AbstractController
{
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }
    #[Route('/', name: 'app_receta_index', methods: ['GET'])]
    public function index(RecetaRepository $recetaRepository, FotoRepository $fotoRepository): Response
    {
        $recetas = $this->entityManager->getRepository(Receta::class)->findAll();
        $ingredientes = [];
        for ($i = 0; $i < count($recetas); $i++) {
            $recetaId = $recetas[$i]->getId();
            $qb = $this->entityManager->createQueryBuilder()
                ->select('i')
                ->from('App\Entity\Ingrediente', 'i')
                ->join('i.recetas', 'r')
                ->where('r.id = :recetaId')
                ->setParameter('recetaId', $recetaId);

            $ingredientesQuery = $qb->getQuery();
            $ingredientes[$i] = $ingredientesQuery->getResult();
        }
        return $this->render('receta/index.html.twig', [
            'recetas' => $recetas,
            'fotos' => $fotoRepository->findAll(),
            'key' => 0,
            'ingredientes' => $ingredientes,
        ]);
    }

    #[Route('/new', name: 'app_receta_new', methods: ['GET', 'POST'])]
    public function new(Request $request, RecetaRepository $recetaRepository): Response
    {
        $recetum = new Receta();
        $form = $this->createForm(Receta1Type::class, $recetum);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $recetaRepository->save($recetum, true);

            return $this->redirectToRoute('app_foto_new', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('receta/new.html.twig', [
            'recetum' => $recetum,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_receta_show', methods: ['GET'])]
    public function show(Receta $recetum): Response
    {
        return $this->render('receta/show.html.twig', [
            'recetum' => $recetum,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_receta_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Receta $recetum, RecetaRepository $recetaRepository): Response
    {
        $form = $this->createForm(Receta1Type::class, $recetum);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $recetaRepository->save($recetum, true);

            return $this->redirectToRoute('app_receta_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('receta/edit.html.twig', [
            'recetum' => $recetum,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_receta_delete', methods: ['POST'])]
    public function delete(Request $request, Receta $recetum, RecetaRepository $recetaRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$recetum->getId(), $request->request->get('_token'))) {
            $recetaRepository->remove($recetum, true);
        }

        return $this->redirectToRoute('app_receta_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/receta/_delete_form.html.twig
<form method="post" action="{{ path('app_receta_delete', {'id': recetum.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recetum.id) }}">
    <button class="btn">Delete</button>
</form>

templates/receta/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Receta{% endblock %}

{% block body %}
    <h1>Edit Receta</h1>

    {{ include('receta/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_receta_index') }}">back to list</a>

    {{ include('receta/_delete_form.html.twig') }}
{% endblock %}

templates/receta/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recetario{% endblock %}

{% block body %}
<style>
    .main {
        display: flex;
        flex-direction: column;
        align-items: center;
        background-color: #f5f5f5;
        width: 60%;
        margin: 0 auto;
        margin-top: 5%;
        gap: 1rem;
        border-radius: 16px;
        padding: 1rem;
        text-align: center;
    }
    .tittle {
        font-size: 3rem;
        font-weight: 400;
        padding: 0;
        margin: 0;
    }

    .receta{
        display: flex;
        flex-direction: column;
        align-items: center;
        border: 1px solid #ccc;
        border-radius: 16px;
        padding: 1rem;
        width: 400px;
        overflow: hidden;
        gap: 1rem;
    }

    .recetaHeader {
        display: flex;
        flex-direction: row;
        align-items: center;
        gap: 1rem;
        justify-content: space-around;
        width: 100%;
    }
    .fotoReceta {
        max-width: 100%;
    }
    .recetaFooter {
        text-align: center;
    }
    .listaIngredientes {
        width: 50%;
        margin: 0 auto;
        padding: 0;
        padding-bottom: 1rem;
    }
    .listaIngredientes li {
        list-style: none;
    }
</style>

<div class="main">
    <h1 class='tittle'>Recetario</h1>

    <a href="{{ path('app_receta_new') }}">Crear receta</a>
    {% for receta in recetas %}
        <div class="receta">
            <div class="recetaHeader">
                <h2>{{ receta.nombre }}</h2>
                <p>{{ receta.tipoReceta }}</p>
            </div>
            <div class="recetaBody">
                <img src={{asset('img/' ~ fotos[key])}} alt='foto de receta' class='fotoReceta'/>
            </div>
            <div class="recetaFooter">
                <details>
                    <summary>Receta</summary>
                    <p><b>Ingredientes</b></p>
                    <ul class='listaIngredientes'>
                        {% for ingrediente in ingredientes[key] %}
                            <li>{{ ingrediente }}</li>
                        {% endfor %}
                    </ul>
                    <p><b>Preparación</b></p>
                    {{ receta.descripcion }}
                </details>
            </div>
        </div>
        {% set key = key + 1 %}
    {% endfor %}
    
</div>
{% endblock %}

templates/receta/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Receta{% endblock %}

{% block body %}
    <style>
        .main {
        display: flex;
        flex-direction: column;
        align-items: center;
        background-color: #f5f5f5;
        width: 60%;
        margin: 0 auto;
        margin-top: 5%;
        gap: 1rem;
        border-radius: 16px;
        padding: 1rem; 
        text-align: center; 
    }

    .tittle {
        font-size: 3rem;
        font-weight: 400;
        padding: 0;
        margin: 0;
    }

    #receta1 {
        display: flex;
        flex-direction: column;
        gap: 1rem;
    }

    #receta1 div {
        display: flex;
        flex-direction: row;
        gap: 1rem;
    }
    </style>
    

    <div class='main'>
        <h1 class="tittle">Create new Receta</h1>

        {{ include('receta/_form.html.twig') }}

        <a href="{{ path('app_receta_index') }}">Volver a las recetas</a>
    </div>
{% endblock %}

templates/receta/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Receta{% endblock %}

{% block body %}
    <h1>Receta</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ recetum.id }}</td>
            </tr>
            <tr>
                <th>Fecha</th>
                <td>{{ recetum.fecha ? recetum.fecha|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Tipo_receta</th>
                <td>{{ recetum.tipoReceta }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ recetum.nombre }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_receta_index') }}">back to list</a>

    <a href="{{ path('app_receta_edit', {'id': recetum.id}) }}">edit</a>

    {{ include('receta/_delete_form.html.twig') }}
{% endblock %}